version: '2'

services:
  basex:
    image: basex/basexhttp:latest
    ports:
     - "1984:1984"
     - "8984:8984"
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database

  es:
    image: elasticsearch:5.1.2
    ports:
     - "9200:9200"

  web:
    build: .
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    
    volumes:
      - ./lacr-demo:/lacr-demo
    ports:
      - "80:3000"
    depends_on:
      - es
      - db
